platform :ios, '13.0'

target 'SCWeibo' do
  use_frameworks!

  # Pods for SCWeibo
  pod "FMDB", '2.7.5'
  pod 'SnapKit', '5.0.1'
  pod "Weibo_SDK",'3.3.0'
  pod 'Alamofire', '5.4.1'
  pod 'Kingfisher', '6.1.1'
  pod 'Neon', '0.4.0'
  pod 'MJRefresh', '3.5.0'
  pod 'SKPhotoBrowser', '6.1.0'
  pod 'SVProgressHUD'
  pod 'SwipeCellKit'
  pod 'MMKV'
  
  # Pods for DEBUG
  pod 'FLEX', '4.4.0', :configurations => ['Debug']

  target 'SCWeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCWeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
