# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCWeibo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SCWeibo
  pod "SDWebImage", '5.6.1'
  pod "YYModel", '1.0.4'
  pod "FMDB", '2.7.5'
  pod 'SVProgressHUD', '2.2.5'
  pod 'SnapKit', '5.0.1'
  pod "Weibo_SDK",'3.3.0'

  pod 'Alamofire', '5.4.1'
  pod 'Kingfisher', '6.1.1'
  pod 'Neon', '0.4.0'
  pod 'BlocksKit'

  # Pods for DEBUG
  pod 'FLEX', '4.4.0', :configurations => ['Debug']


  target 'SCWeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCWeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
